#ifndef SENSORS_H
#define SENSORS_H

#include <Msp430Adc12.h>

enum {
  ADC0,
  ADC1,
  ADC2,
  ADC3,
  ADC6,
  ADC7,
  // add more entries here
  VOLT,
  // last entry
  SENSOR_SENTINEL
};

const msp430adc12_channel_config_t sensorconfigurations[] = {
    /* ADC0 */
    { INPUT_CHANNEL_A0, REFERENCE_VREFplus_AVss, REFVOLT_LEVEL_2_5,
      SHT_SOURCE_ACLK, SHT_CLOCK_DIV_1, SAMPLE_HOLD_4_CYCLES,
      SAMPCON_SOURCE_ACLK, SAMPCON_CLOCK_DIV_1
    },
    /* ADC1 */
    { INPUT_CHANNEL_A1, REFERENCE_VREFplus_AVss, REFVOLT_LEVEL_2_5,
      SHT_SOURCE_ACLK, SHT_CLOCK_DIV_1, SAMPLE_HOLD_4_CYCLES,
      SAMPCON_SOURCE_ACLK, SAMPCON_CLOCK_DIV_1
    },
    /* ADC2 */
    { INPUT_CHANNEL_A2, REFERENCE_VREFplus_AVss, REFVOLT_LEVEL_2_5,
      SHT_SOURCE_ACLK, SHT_CLOCK_DIV_1, SAMPLE_HOLD_4_CYCLES,
      SAMPCON_SOURCE_ACLK, SAMPCON_CLOCK_DIV_1
    },
    /* ADC3 */
    { INPUT_CHANNEL_A3, REFERENCE_VREFplus_AVss, REFVOLT_LEVEL_2_5,
      SHT_SOURCE_ACLK, SHT_CLOCK_DIV_1, SAMPLE_HOLD_4_CYCLES,
      SAMPCON_SOURCE_ACLK, SAMPCON_CLOCK_DIV_1
    },
    /* ADC6 */
    { INPUT_CHANNEL_A6, REFERENCE_VREFplus_AVss, REFVOLT_LEVEL_2_5,
      SHT_SOURCE_ACLK, SHT_CLOCK_DIV_1, SAMPLE_HOLD_4_CYCLES,
      SAMPCON_SOURCE_ACLK, SAMPCON_CLOCK_DIV_1
    },
    /* ADC7 */
    { INPUT_CHANNEL_A7, REFERENCE_VREFplus_AVss, REFVOLT_LEVEL_2_5,
      SHT_SOURCE_ACLK, SHT_CLOCK_DIV_1, SAMPLE_HOLD_4_CYCLES,
      SAMPCON_SOURCE_ACLK, SAMPCON_CLOCK_DIV_1
    },
    /* VOLT */
    {
      SUPPLY_VOLTAGE_HALF_CHANNEL, REFERENCE_VREFplus_AVss, REFVOLT_LEVEL_2_5,
      SHT_SOURCE_ACLK, SHT_CLOCK_DIV_1, SAMPLE_HOLD_4_CYCLES, SAMPCON_SOURCE_SMCLK,
      SAMPCON_CLOCK_DIV_1
  	},
    /* your stuff here */
    /* SENSOR_SENTINEL */
    {
        INPUT_CHANNEL_NONE,0,0,0,0,0,0,0
    }
};


#endif
