COMPONENT=EasyDisseminationAppC

### For original Drip:
#CFLAGS += -I$(TOSDIR)/lib/net 
#CFLAGS += -I%T/lib/net/drip

### For Simpledrip
CFLAGS += -I../../SimpleDrip

CFLAGS += -DCC2420_DEF_CHANNEL=13
CFLAGS += -DRF230_DEF_CHANNEL=13

include $(MAKERULES)
