COMPONENT=GoldenImageAppC
BOOTLOADER=tosboot

# Define radio channel
CFLAGS += -DCC2420_DEF_CHANNEL=26
CFLAGS += -DRF230_DEF_CHANNEL=26 

#CFLAGS+=-DDELUGE_LIGHT_BASESTATION

# path to SimpleDrip
CFLAGS += -I../../SimpleDrip

include $(MAKERULES)
